services:
  postgres:
    image: postgres:15
    container_name: calendar_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d ${PG_DATABASE}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: calendar_rabbitmq
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  migration:
    build:
      context: .
      dockerfile: ./build/Dockerfile_migration
    container_name: calendar_migration
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_DBNAME: ${PG_DATABASE}
      DATABASE_HOST: calendar_postgres
    volumes:
      - ./configs:/etc/calendar:ro
      - ./migrations:/migrations:ro

  calendar:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    container_name: calendar_app
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    environment:
      DATABASE_DBNAME: ${PG_DATABASE}
      DATABASE_HOST: calendar_postgres
      RABBITMQ_HOST: calendar_rabbitmq
    ports:
      - "8080:8080"
      - "50055:50055"
    volumes:
      - ./configs:/etc/calendar:ro
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://127.0.0.1:8080/ping || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  scheduler:
    build:
      context: .
      dockerfile: ./build/Dockerfile_scheduler
    container_name: calendar_scheduler
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    environment:
      DATABASE_DBNAME: ${PG_DATABASE}
      DATABASE_HOST: calendar_postgres
      RABBITMQ_HOST: calendar_rabbitmq
    volumes:
      - ./configs:/etc/calendar:ro

  sender:
    build:
      context: .
      dockerfile: ./build/Dockerfile_sender
    container_name: calendar_sender
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    environment:
      RABBITMQ_HOST: calendar_rabbitmq
    volumes:
      - ./configs:/etc/calendar:ro

volumes:
  postgres_data: