services:

  postgres:
    image: postgres:15
    container_name: calendar_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: calendar
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d calendar" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: calendar_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: .
      dockerfile: ./build/Dockerfile_migration
    container_name: calendar_migration
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CONFIG_FILE: /etc/calendar/config.yaml
    volumes:
      - ./configs:/etc/calendar:ro
      - ./migrations:/migrations:ro
    restart: on-failure

  calendar:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    container_name: calendar_app
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    ports:
      - "8085:8085"
      - "50055:50055"
    environment:
      CONFIG_FILE: /etc/calendar/config.yaml
    volumes:
      - ./configs:/etc/calendar:ro

volumes:
  postgres_data: