app:
  # example: "memory" | "sql"
  storage: "sql"

  # example: "http" | "grpc" | "both"
  server: "both"

  # Периодичность выполнения планировщика (в секундах)
  timeout_scheduler: 10

logger:
  # example: "debug" | "info" | "warn" | "warning" | "error"
  level: "debug"

  # example: "text_color" | "text" | "json"
  handler: "text_color"

  # write to file if this option is not empty, example "logfile.log"
  # and it is recommended to change the handler to "json"
  filename: ""

  add_source: true

server:
  http_addr: "localhost:8085"
  grpc_addr: "localhost:50055"

database:
  username: "root"
  password: "root"
  dbname: "calendar"
  host: "localhost"
  port: 5433

rabbitmq:
  username: "guest"
  password: "guest"
  queue: "events"   # Название очереди для уведомлений
  host: "localhost"
  port: 5672
