app:
  storage: "memory"           # example: "memory" | "sql"
  server: "grpc"              # example: "http" | "grpc" | "both"

logger:
  level: "debug"              # example: "debug" | "info" | "warn" | "warning" | "error"
  handler: "text_color"       # example: "text_color" | "text" | "json"
  filename: ""                # write to file if this option is not empty, example: "logfile.log"
  add_source: true

server:
  http_addr: "localhost:8081"
  grpc_addr: "localhost:50051"

database:
  host: "database.host"
  port: 5432